// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for C and C++
// from codepoints style.css
// for use with font icomoon.ttf

#pragma once

#define FONT_ICON_FILE_NAME_ICOMN "icomoon.ttf"

#define ICON_MIN_ICOMN 0xe902
#define ICON_MAX_16_ICMN 0xea38
#define ICON_MAX_ICOMN 0xea38

#define ICON_ICOMN_HOME3 "\xee\xa4\x82"         // U+e902
#define ICON_ICOMN_IMAGE "\xee\xa4\x8d"         // U+e90d
#define ICON_ICOMN_IMAGES "\xee\xa4\x8e"        // U+e90e
#define ICON_ICOMN_VIDEO_CAMERA "\xee\xa4\x94"  // U+e914
#define ICON_ICOMN_FILE_EMPTY "\xee\xa4\xa4"    // U+e924
#define ICON_ICOMN_FILE_PICTURE "\xee\xa4\xa7"  // U+e927
#define ICON_ICOMN_FOLDER "\xee\xa4\xaf"        // U+e92f
#define ICON_ICOMN_FOLDER_OPEN "\xee\xa4\xb0"   // U+e930
#define ICON_ICOMN_FOLDER_PLUS "\xee\xa4\xb1"   // U+e931
#define ICON_ICOMN_FOLDER_MINUS "\xee\xa4\xb2"  // U+e932
#define ICON_ICOMN_FLOPPY_DISK "\xee\xa5\xa2"   // U+e962
#define ICON_ICOMN_DRIVE "\xee\xa5\xa3"         // U+e963
#define ICON_ICOMN_DATABASE "\xee\xa5\xa4"      // U+e964
#define ICON_ICOMN_SEARCH "\xee\xa6\x86"        // U+e986
#define ICON_ICOMN_ZOOM_IN "\xee\xa6\x87"       // U+e987
#define ICON_ICOMN_ZOOM_OUT "\xee\xa6\x88"      // U+e988
#define ICON_ICOMN_LOCK "\xee\xa6\x8f"          // U+e98f
#define ICON_ICOMN_UNLOCKED "\xee\xa6\x90"      // U+e990
#define ICON_ICOMN_BIN "\xee\xa6\xac"           // U+e9ac
#define ICON_ICOMN_LIST_NUMBERED "\xee\xa6\xb9" // U+e9b9
#define ICON_ICOMN_LIST "\xee\xa6\xba"          // U+e9ba
#define ICON_ICOMN_LIST2 "\xee\xa6\xbb"         // U+e9bb
#define ICON_ICOMN_TREE "\xee\xa6\xbc"          // U+e9bc
#define ICON_ICOMN_MENU "\xee\xa6\xbd"          // U+e9bd
#define ICON_ICOMN_MENU2 "\xee\xa6\xbe"         // U+e9be
#define ICON_ICOMN_MENU3 "\xee\xa6\xbf"         // U+e9bf
#define ICON_ICOMN_MENU4 "\xee\xa7\x80"         // U+e9c0
#define ICON_ICOMN_CROSS "\xee\xa8\x8f"         // U+ea0f
#define ICON_ICOMN_PLAY3 "\xee\xa8\x9c"         // U+ea1c
#define ICON_ICOMN_PAUSE2 "\xee\xa8\x9d"        // U+ea1d
#define ICON_ICOMN_STOP2 "\xee\xa8\x9e"         // U+ea1e
#define ICON_ICOMN_ARROW_RIGHT "\xee\xa8\xb4"   // U+ea34
#define ICON_ICOMN_ARROW_LEFT "\xee\xa8\xb8"    // U+ea38
